name: cmsc433test
version: '0.2.0.0'

dependencies:
- base
- liquidhaskell-boot
- liquid-prelude
- liquidhaskell
- transformers

library:
  ghc-options: -fplugin=LiquidHaskell

  source-dirs:
    - src

  exposed-modules:
    - P4Solutions