resolver: lts-20.1
packages:
  - .
extra-deps:
  # - Diff-0.3.4
  # - text-format-0.3.2
  - rest-rewrite-0.4.1
  - smtlib-backends-0.3
  - smtlib-backends-process-0.3
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: 89d4ec273372510c9092a06b7b21b671c5733731
    subdirs:
      - .
      - liquidhaskell-boot
      - liquid-prelude
      - liquid-vector
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: 1aab5d84e3dd96f3052dd27b92316cbb5254def1


